name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'  # Trigger only when files in the backend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run tests
        run: pipenv run test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Build Docker Image
        run: docker build -t my-backend:latest .
      - name: Tag Docker Image
        run: docker tag my-backend:latest ${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push Docker Image to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_F }}
          docker push ${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}
      - name: Deploy to Kubernetes
        run: |
          kustomize edit set image backend=${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}
          kustomize build | kubectl apply -f -