name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Trigger only when files in the frontend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: npm test
        working-directory: frontend

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t my-frontend:latest .
        working-directory: frontend
      - name: Tag Docker Image
        run: docker tag my-frontend:latest <ECR_REPO_URL>:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push Docker Image to ECR
        run: |
          aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <ECR_REPO_URL>
          docker push <ECR_REPO_URL>:${{ github.sha }}
      - name: Deploy to Kubernetes
        run: |
          kustomize edit set image frontend=<ECR_REPO_URL>:${{ github.sha }}
          kustomize build | kubectl apply -f -