name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'  # Trigger only when files in the backend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Run Tests
        run: npm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Build Docker Image
        run: 
          # docker build --build-arg REACT_APP_MOVIE_API_URL=${{ env.REACT_APP_MOVIE_API_URL }} -t my-frontend:latest .
          docker build -t my-frontend:latest .

  post-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: output/