name: Frontend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'  # Trigger only when files in the backend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Run Tests
        run: npm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Build Docker Image
        run: docker build -t my-frontend:latest .
        

  # comment:
  #   needs: [lint, test, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Comment on PR
  #       if: always() # Ensures this step runs even if previous steps fail
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           const { context, github } = require('@actions/github');
  #           const comment = {
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             issue_number: context.issue.number,
  #             body: 'CI Pipeline completed. Check the results above.'
  #           };
  #           github.rest.issues.createComment(comment);