name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Trigger only when files in the frontend directory change
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Run Tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Setup Project
        uses: wallylannister/cd12354-Movie-Picture-Pipeline@main
        with:
          node-version: '18'
      - name: Build Docker Image
        run: docker build -t my-frontend:latest .
        working-directory: frontend
      - name: Tag Docker Image
        run: docker tag my-frontend:latest ${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push Docker Image to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_F }}
          docker push ${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}
      - name: Deploy to Kubernetes
        run: |
          kustomize edit set image frontend=${{ secrets.ECR_REGISTRY_F }}:${{ github.sha }}
          kustomize build | kubectl apply -f -